/*
 * IncidentLog API
 *
 * Incident reporting and security event management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package incident_log

import (
	"github.com/gin-gonic/gin"
)

type IncidentLogsAPI interface {


    // CreateIncidentLog Post /api/incident-log
    // Saves new incident log definition 
     CreateIncidentLog(c *gin.Context)

    // DeleteIncidentLog Delete /api/incident-log/:incidentLogId
    // Deletes specific incident log 
     DeleteIncidentLog(c *gin.Context)

}