/*
 * IncidentLog API
 *
 * Incident reporting and security event management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package incident_log

import (
	"github.com/gin-gonic/gin"
)

type IncidentTypesAPI interface {


    // GetIncidentTypes Get /api/incident-types
    // Provides the list of predefined incident types 
     GetIncidentTypes(c *gin.Context)

}