/*
 * IncidentLog API
 *
 * Incident reporting and security event management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package incident_log

import (
	"github.com/gin-gonic/gin"
)

type IncidentLogAPI interface {


    // CreateIncident Post /api/incidents
    // Saves new incident 
     CreateIncident(c *gin.Context)

    // DeleteIncident Delete /api/incidents/:incidentId
    // Deletes specific incident 
     DeleteIncident(c *gin.Context)

    // GetIncident Get /api/incidents/:incidentId
    // Provides details about incident 
     GetIncident(c *gin.Context)

    // GetIncidents Get /api/incidents
    // Provides the list of incidents 
     GetIncidents(c *gin.Context)

    // UpdateIncident Put /api/incidents/:incidentId
    // Updates specific incident 
     UpdateIncident(c *gin.Context)

}