/*
 * IncidentLog API
 *
 * Incident reporting and security event management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package incident_log
// IncidentSeverity : Severity level of the incident
type IncidentSeverity string

// List of IncidentSeverity
const (
	NZKA IncidentSeverity = "Nízka"
	STREDN IncidentSeverity = "Stredná"
	VYSOK IncidentSeverity = "Vysoká"
	KRITICK IncidentSeverity = "Kritická"
)
