/*
 * IncidentLog API
 *
 * Incident reporting and security event management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package incident_log

import (
	"time"
)

type Incident struct {

	// Unique id of the incident
	Id string `json:"id"`

	// Type of the incident
	IncidentType string `json:"incidentType"`

	// Place where the incident occurred
	Location string `json:"location"`

	// Date and time when the incident occurred
	OccurredAt time.Time `json:"occurredAt"`

	// Description of the incident
	Description string `json:"description"`

	Severity IncidentSeverity `json:"severity"`

	Status IncidentStatus `json:"status"`

	// List of attached files
	Attachments []string `json:"attachments,omitempty"`

	// Investigation report
	InvestigationReport string `json:"investigationReport,omitempty"`

	// Additional notes
	Notes string `json:"notes,omitempty"`
}
