/*
 * IncidentLog API
 *
 * Incident reporting and security event management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package incident_log

type IncidentType struct {

	Code string `json:"code"`

	Value string `json:"value"`

	TypicalSeverity IncidentSeverity `json:"typicalSeverity,omitempty"`

	Description string `json:"description,omitempty"`
}
