/*
 * IncidentLog API
 *
 * Incident reporting and security event management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package incident_log
// IncidentStatus : Current resolution status of the incident
type IncidentStatus string

// List of IncidentStatus
const (
	NOV IncidentStatus = "Nový"
	V_RIEEN IncidentStatus = "V riešení"
	UZATVOREN IncidentStatus = "Uzatvorený"
)
