/*
 * IncidentLog API
 *
 * Incident reporting and security event management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package incident_log

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name		string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method		string
	// Pattern is the pattern of the URI.
	Pattern	 	string
	// HandlerFunc is the handler function of this route.
	HandlerFunc	gin.HandlerFunc
}

// NewRouter returns a new router.
func NewRouter(handleFunctions ApiHandleFunctions) *gin.Engine {
	return NewRouterWithGinEngine(gin.Default(), handleFunctions)
}

// NewRouter add routes to existing gin engine.
func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	for _, route := range getRoutes(handleFunctions) {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

type ApiHandleFunctions struct {

	// Routes for the IncidentLogAPI part of the API
	IncidentLogAPI IncidentLogAPI
	// Routes for the IncidentLogsAPI part of the API
	IncidentLogsAPI IncidentLogsAPI
	// Routes for the IncidentTypesAPI part of the API
	IncidentTypesAPI IncidentTypesAPI
}

func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	return []Route{ 
		{
			"CreateIncident",
			http.MethodPost,
			"/api/incidents",
			handleFunctions.IncidentLogAPI.CreateIncident,
		},
		{
			"DeleteIncident",
			http.MethodDelete,
			"/api/incidents/:incidentId",
			handleFunctions.IncidentLogAPI.DeleteIncident,
		},
		{
			"GetIncident",
			http.MethodGet,
			"/api/incidents/:incidentId",
			handleFunctions.IncidentLogAPI.GetIncident,
		},
		{
			"GetIncidents",
			http.MethodGet,
			"/api/incidents",
			handleFunctions.IncidentLogAPI.GetIncidents,
		},
		{
			"UpdateIncident",
			http.MethodPut,
			"/api/incidents/:incidentId",
			handleFunctions.IncidentLogAPI.UpdateIncident,
		},
		{
			"CreateIncidentLog",
			http.MethodPost,
			"/api/incident-log",
			handleFunctions.IncidentLogsAPI.CreateIncidentLog,
		},
		{
			"DeleteIncidentLog",
			http.MethodDelete,
			"/api/incident-log/:incidentLogId",
			handleFunctions.IncidentLogsAPI.DeleteIncidentLog,
		},
		{
			"GetIncidentTypes",
			http.MethodGet,
			"/api/incident-types",
			handleFunctions.IncidentTypesAPI.GetIncidentTypes,
		},
	}
}
